name: wol_cli
version: 1.0.2
description: A CLI application to send Wake-On-Lan packets.
repository: https://github.com/fluttercandies/dart_wake_on_lan

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  args: ^2.1.0
  wake_on_lan: ^3.2.0

dev_dependencies:
  lints: any

executables:
  wol: wol
