name: wol_cli
version: 2.0.0+1
description: A CLI application to send Wake-On-Lan packets to specified destination including IP / Domain Host + port.
repository: https://github.com/fluttercandies/dart_wake_on_lan

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.5.0
  wake_on_lan: ^4.1.0

dev_dependencies:
  lints: any

executables:
  wol: wol
